management.endpoints.web.exposure.include: "*"
vehicleCount : 25
messageCount : 10000
distanceIncrements : 1
streamName : VehicleStream
delayMs : 1
vinPrefix: G
server:
  port: 0
springdoc.api-docs.path: /api-docs
spring:
  task:
    execution:
      pool:
        max-size: 8
  application.name: generateVehicleSource
rabbitmq:
  streaming:
    uris: rabbitmq-stream://guest:guest@localhost:5552
    stream:
      maxAgeHours: 1
      maxLengthGb: 5
      maxSegmentSizeMb: 500