#streamName : VehicleStream
replay: false
management.endpoints.web.exposure.include: "*"
server:
 port: 9001
rabbitmq:
 streaming:
  uris: rabbitmq-stream://vehicle:security@localhost:5552
  stream:
   maxAgeHours: 1
   maxLengthGb: 90
   maxSegmentSizeMb: 500
  replay: false
  name : VehicleStream
spring:
  application.name: vehicle-telemetry-jdbc-streaming-sink
  flyway:
#   url: jdbc:postgresql://localhost:5432/postgres
#   user: postgres
#   password: security
   locations: "classpath:db/migration"
  jpa:
   hibernate:
    ddl-auto: create
   generate-ddl: true
  datasource:
   url: jdbc:postgresql://localhost:5432/postgres
   username: postgres
   password: security

