apiVersion: gemfire.vmware.com/v1
kind: GemFireCluster
metadata:
  name: gemfire
spec:
  image: registry.tanzu.vmware.com/pivotal-gemfire/vmware-gemfire:10.0.2
  # Set antiAffinityPolicy to "Cluster" or "Full" in production to limit the
  # chance of data loss.
  antiAffinityPolicy: None
  security:
    tls: {}
  metrics:
    emission: Default
  locators:
    replicas: 2
    resources:
      requests:
        memory: 1Gi
  servers:
    replicas: 2
    resources:
      requests:
        memory: 1Gi