apiVersion: gemfire.vmware.com/v1
kind: GemFireCluster
metadata:
  name: gemfire
spec:
  image: registry.tanzu.vmware.com/pivotal-gemfire/vmware-gemfire:10.0.2
  # Set antiAffinityPolicy to "Cluster" or "Full" in production to limit the
  # chance of data loss.
  antiAffinityPolicy: None
  security:
    tls: {}
  metrics:
    emission: Default
  locators:
    replicas: 2
    resources:
      requests:
        memory: 1Gi
    overrides:
      gemFireProperties:
        - name : "start-dev-rest-api"
          value : "true"
  servers:
    replicas: 2
    resources:
      requests:
        memory: 1Gi
    overrides:
      gemFireProperties:
        - name : "start-dev-rest-api"
          value : "true"
---
apiVersion: v1
kind: Service
metadata:
  name: gemfire-locator-lb
spec:
  selector:
    gemfire.vmware.com/app: gemfire-locator
  ports:
    - name: management
      port: 7070
      targetPort: 7070
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  type: LoadBalancer