rabbitmq:
 streaming:
   uris: rabbitmq-stream://guest:guest@localhost:5552
   stream:
     maxAgeHours: 1
     maxLengthGb: 5
     maxSegmentSizeMb: 500
   replay: false
   name : VehicleStream
management.endpoints.web.exposure.include: "*"
server:
 port: 0
spring:
  application.name: vehicle-streaming-geode-sink
