apiVersion: v1
kind: Pod
metadata:
  name: rabbitmq-perftest
  labels:
    run: rabbitmq-perftest
spec:
  containers:
    - name: rabbitmq-perftest
      image: pivotalrabbitmq/stream-perf-test
      imagePullPolicy: Always
      args: ["--uris", "${RABBIT_URIS}"]
      env:
        - name: RABBIT_URIS
          valueFrom:
            secretKeyRef:
              name: vehicle-secrets
              key: rabbitmq-stream_uris