server:
  port: 0
spring:
  application.name: VehicleGeodeSink
  data:
    gemfire:
      pool:
        default:
          locators: "localhost[10334]"
  cloud:
    function.definition: vehicleRepositorySink
    stream:
      bindings:
        vehicleRepositorySink-in-0:
          destination: vehicleSink
          group: vehicleRepositorySink
          consumer:
            concurrency: 2
      rabbit:
        bindings:
          vehicleRepositorySink-in-0:
            consumer:
              autoBindDlq: true
              quorum.enabled: true
              prefetch: 10000
        default:
          quorum.enabled: true
          autoBindDlq: true