apiVersion: v1
kind: Pod
metadata:
  labels:
    run:  vehicles-geode-sink
  name:  vehicles-geode-sink
spec:
  containers:
    - env:
        - name: spring.rabbitmq.host
          value: rabbitmq
        - name: spring_rabbitmq_username
          valueFrom:
            secretKeyRef:
              name: vehicle-secrets
              key: spring_rabbitmq_username
        - name: spring_rabbitmq_password
          valueFrom:
            secretKeyRef:
              name: vehicle-secrets
              key: spring_rabbitmq_password
        - name: spring.data.gemfire.pool.locators
          valueFrom:
            configMapKeyRef:
              name: vehicle-configmap
              key: spring.data.gemfire.pool.locators
      image: nyla/vehicles-geode-sink:0.0.1-SNAPSHOT
      imagePullPolicy: Always
      name: vehicles-geode-sink
