apiVersion: v1
kind: Pod
metadata:
  name: vehicle-generator-source-a
  labels:
    run: vehicle-generator-source-a
spec:
  containers:
    - name: vehicle-generator-source-a
      image: nyla/vehicle-generator-source:0.0.4-SNAPSHOT
      resources:
        requests:
          memory: "5Gi"
      imagePullPolicy: Always
      env:
        - name: "JVM_ARGS"
          value: "-Xms4g -Xmx4g"
        - name: vehicleCount
          value: "25"
        - name: messageCount
          value: "10000"
        - name: distanceIncrements
          value: "1"
        - name: delayMs
          value: "5"
        - name: vinPrefix
          value: "FLEET-A"
        - name: spring_rabbitmq_host
          value: rabbitmq
        - name: spring_rabbitmq_username
          valueFrom:
            secretKeyRef:
              name: vehicle-secrets
              key: spring_rabbitmq_username
        - name: spring_rabbitmq_password
          valueFrom:
            secretKeyRef:
              name: vehicle-secrets
              key: spring_rabbitmq_password
        - name: spring.data.gemfire.pool.locators
          valueFrom:
            configMapKeyRef:
              name: vehicle-configmap
              key: spring.data.gemfire.pool.locators