streamName : VehicleStream
replay: false
management.endpoints.web.exposure.include: "*"

server:
 port: 9001
spring:
 application.name: vehicles-mqtt-geode-sink
 mvc:
  pathmatch:
   matching-strategy: ANT_PATH_MATCHER