apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmq
spec:
  replicas: 3
  image: pivotalrabbitmq/rabbitmq-stream
  resources:
    requests:
      cpu: 3000m
      memory: 10Gi
    limits:
      cpu: 3000m
      memory: 10Gi
  persistence:
    storage: 20Gi
  rabbitmq:
    additionalPlugins:
      - rabbitmq_mqtt
      - rabbitmq_shovel
      - rabbitmq_stream
      - rabbitmq_stream_management
      - rabbitmq_stream_prometheus