apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmq
spec:
  replicas: 3
  image: pivotalrabbitmq/rabbitmq-stream
  resources:
    requests:
      cpu: 300m
      memory: 700Mi
    limits:
      cpu: 300m
      memory: 700Mi