apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmq
spec:
  replicas: 3
  image: pivotalrabbitmq/rabbitmq-stream
  resources:
    requests:
      cpu: 3000m
      memory: 18Gi
    limits:
      cpu: 3000m
      memory: 18Gi
  rabbitmq:
    additionalPlugins:
      - rabbitmq_mqtt
      - rabbitmq_shovel
      - rabbitmq_stream
      - rabbitmq_stream_management
      - rabbitmq_stream_prometheus
  override:
    service:
      spec:
        ports:
          - name: streaming-port # adds an additional port on the service
            protocol: TCP
            port: 5552
    statefulSet:
      spec:
        template:
          spec:
            containers:
              - name: rabbitmq
                ports:
                  - containerPort: 5552 # opens an additional port on the rabbitmq server container
                    name: streaming-port
                    protocol: TCP