apiVersion: v1
kind: Pod
metadata:
  labels:
    run:  iot-connected-vehicles-sink
  name:  iot-connected-vehicles-sink
spec:
  containers:
    - env:
        - name: spring.rabbitmq.host
          value: rabbitmq
        - name: spring.rabbitmq.username
          valueFrom:
            secretKeyRef:
              name: rabbitmq-default-user
              key: username
        - name: spring.rabbitmq.password
          valueFrom:
            secretKeyRef:
              name: rabbitmq-default-user
              key: password
        - name: LOCATORS
          valueFrom:
            configMapKeyRef:
              name: vehicle-configmap
              key: spring.data.gemfire.pool.locators
      image: iot-connected-vehicles-sink:0.0.1-SNAPSHOT
      name: iot-connected-vehicles-sink
