apiVersion: v1
kind: Pod
metadata:
  labels:
    run:  vehicles-geode-sink
  name:  vehicles-geode-sink
spec:
  containers:
    - env:
        - name: spring.rabbitmq.host
          value: rabbitmq
#        - name: spring.rabbitmq.username
#          valueFrom:
#            secretKeyRef:
#              name: rabbitmq-default-user
#              key: username
#        - name: spring.rabbitmq.password
#          valueFrom:
#            secretKeyRef:
#              name: rabbitmq-default-user
#              key: password
        - name: spring.data.gemfire.pool.locators
          valueFrom:
            configMapKeyRef:
              name: gemfire1-config
              key: locators
      image: vehicles-geode-sink:0.0.4-SNAPSHOT
      name: vehicles-geode-sink
