apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: vehicle-generator-app
  name: vehicle-generator-app
spec:
  containers:
    - env:
        - name: spring.example
          value: test
      image: vehicle-generator-app:0.0.1-SNAPSHOT
      name: vehicle-generator-app
      resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
