apiVersion: v1
kind: Pod
metadata:
  labels:
    run: vehicle-generator-source
  name: vehicle-generator-source
spec:
  containers:
    - env:
#        - name: vehicleCount
#          value: "25"
#        - name: messageCount
#          value: "100000"
#        - name: distanceIncrements
#          value: "1"
#        - name: delayMs
#          value: "10"
        - name: spring.rabbitmq.host
          value: rabbitmq
        - name: vehicleCount
          valueFrom:
            configMapKeyRef:
              name: vehicle-configmap
              key: vehicleCount
        - name: messageCount
          valueFrom:
            configMapKeyRef:
              name: vehicle-configmap
              key: messageCount
        - name: distanceIncrements
          valueFrom:
            configMapKeyRef:
              name: vehicle-configmap
              key: distanceIncrements
        - name: delayMs
          valueFrom:
            configMapKeyRef:
              name: vehicle-configmap
              key: delayMs
      image: vehicle-generator-source:0.0.4-SNAPSHOT
      name: vehicle-generator-source
