apiVersion: v1
kind: Pod
metadata:
  name: vehicle-generator-streaming-source-vi
  labels:
    run: vehicle-generator-streaming-source-vi
spec:
  containers:
    - name: vehicle-generator-streaming-source-vi
      image: nyla/vehicle-generator-streaming-source:0.0.4-SNAPSHOT
      resources:
        requests:
          cpu: "2000m"
          memory: "5Gi"
      imagePullPolicy: Always
      env:
        - name: "JVM_ARGS"
          value: "-Xms4g -Xmx4g"
        - name: "spring.application.name"
          value: "vehicle-generator-streaming-source-vi"
        - name: vehicleCount
          value: "25"
        - name: vinPrefix
          value: "vi"
        - name: rabbitmq_streaming_stream_maxLengthGb
          valueFrom:
            configMapKeyRef:
              name: vehicle-configmap
              key: rabbitmq_streaming_stream_maxLengthGb
        - name: messageCount
          value: "10000"
        - name: batchSize
          value: "10000"
        - name: subEntrySize
          value: "1000"
        - name: maxUnconfirmedMessages
          value: "20000"
        - name: distanceIncrements
          value: "1"
        - name: delayMs
          value: "0"
        - name: rabbitmq_streaming_uris
          value: rabbitmq-stream://vehicle:security@rabbitmq:5552
        - name: spring_rabbitmq_host
          value: rabbitmq
        - name: spring_rabbitmq_username
          valueFrom:
            secretKeyRef:
              name: vehicle-secrets
              key: spring_rabbitmq_username
        - name: spring_rabbitmq_password
          valueFrom:
            secretKeyRef:
              name: vehicle-secrets
              key: spring_rabbitmq_password