apiVersion: v1
kind: Pod
metadata:
  name: vehicle-generator-source
  labels:
    run: vehicle-generator-source
spec:
  containers:
    - name: vehicle-generator-source
      image: nyla/vehicle-generator-source:0.0.3-SNAPSHOT
      imagePullPolicy: Always
      env:
        - name: vehicleCount
          value: "5"
        - name: messageCount
          value: "100000"
        - name: distanceIncrements
          value: "2"
        - name: delayMs
          value: "10"
        - name: vinPrefix
          value: "G"
        - name: spring_rabbitmq_host
          value: rabbitmq
        - name: spring_rabbitmq_username
          valueFrom:
            secretKeyRef:
              name: vehicle-secrets
              key: spring_rabbitmq_username
        - name: spring_rabbitmq_password
          valueFrom:
            secretKeyRef:
              name: vehicle-secrets
              key: spring_rabbitmq_password
        - name: spring.data.gemfire.pool.locators
          valueFrom:
            configMapKeyRef:
              name: vehicle-configmap
              key: spring.data.gemfire.pool.locators