management.endpoints.web.exposure.include: "*"
server:
 port: 9020
flyway:
 locations: "filesystem:/Users/Projects/VMware/Tanzu/IoT/dev/IoT-connected-vehicles-showcase/applications/vehicles-jdbc-sink/src/main/resources/db/migration"
spring:
  flyway:
#    url: jdbc:postgresql://localhost:5432/postgres
#    user: postgres
#    password: security
    locations: "classpath:db/migration"
  jpa:
    hibernate:
      ddl-auto: none
    generate-ddl: true
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: security
  application.name: VehicleTelemetryelemetryRepositorySink
  cloud:
    function.definition: vehicleTelemetryRepositorySink
    stream:
      bindings:
        vehicleTelemetryRepositorySink-in-0:
          destination: vehicleSink
          group: vehicleTelemetryRepositorySink
#          queueNameGroupOnly: true
          consumer:
            concurrency: 1
      rabbit:
        bindings:
          vehicleTelemetryRepositorySink-in-0:
            consumer:
              autoBindDlq: true
              quorum.enabled: true
              prefetch: 10000
        default:
          quorum.enabled: true
          autoBindDlq: true